In [1]:
# importacion general de librerias y de visualizacion (matplotlib y seaborn)
import pandas as pd
import numpy as np
import random
import re

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs

import warnings
warnings.filterwarnings('ignore')

In [2]:
train_data = pd.read_csv('~/Documents/Datos/DataSets/TP2/train_featured.csv')
test_data = pd.read_csv('~/Documents/Datos/DataSets/TP2/test_featured.csv')
train_data.head()

,id_original,keyword_original,location_original,text_original,target_label,special_chars_count,hashtags,labels,hashtags_count,labels_count,num_chars_count,links_count,clean_text,text_length,mean_word_length,vowels_count,short_words_count,stopwords_count,words_count
0,1,NaN,NaN,our deeds are the reason of this earthquake ma...,1,1,#earthquake,NaN,1,0,0,0,deeds reason earthquake may allah forgive us,68,4.31,25,7,6,13
1,4,NaN,NaN,forest fire near la ronge sask canada,1,1,NaN,NaN,0,0,0,0,forest fire near la ronge sask canada,37,4.43,13,1,0,7
2,5,NaN,NaN,all residents asked to shelter in place are be...,1,3,NaN,NaN,0,0,0,0,residents asked shelter place notified officer...,130,4.95,45,9,11,22
3,6,NaN,NaN,people receive wildfires evacuation orders in ...,1,2,#wildfires,NaN,1,0,5,0,people receive wildfires evacuation orders cal...,56,7.14,24,1,1,7
4,7,NaN,NaN,just got sent this photo from ruby alaska as s...,1,2,#alaska #wildfires,NaN,2,0,0,0,got sent photo ruby alaska smoke wildfires pou...,85,4.38,25,3,7,16

In [3]:
#from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
#from sklearn.pipeline import Pipeline
#from sklearn.linear_model import SGDClassifier
#from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text  import TfidfVectorizer

count_vect = CountVectorizer(stop_words='english')
X_train_counts = count_vect.fit_transform(train_data['clean_text'])
X_train_counts.shape

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB()),
                    ])

text_clf = text_clf.fit(train.clean_text, train.target_label)

predicted = text_clf.predict(test.clean_text)
np.mean(predicted == test.target_label)

In [4]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(train_data.clean_text)
tf_idf = pd.DataFrame(data = X.toarray(), columns=vectorizer.get_feature_names())
tf_idf

,aa,aaa,aaaand,aaalll,aaarrrgghhh,aaemiddleaged,aal,aan,aannnd,aar,...,zones,zonewolf,zoom,zotar,zouma,zrnf,zss,zumiez,zurich,zzz
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7609,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7610,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7611,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7612,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [5]:
tf_idf_featured = pd.concat([train_data['target_label'], tf_idf], axis=1)

In [6]:
#tf_idf_featured.drop(['index', 'id_original', 'text_original', 'clean_text', 'keyword_original', 'location_original', 'hashtags', 'labels'], axis=1, inplace=True)

In [13]:
train, test = train_test_split(tf_idf_featured, test_size=0.2)

In [14]:
clf = MultinomialNB()
clf.fit(train.drop(['target_label'], axis=1), train.target_label)

MultinomialNB()

In [15]:
predicted = clf.predict(test.drop(['target_label'], axis=1))
np.mean(predicted == test.target_label)

0.7984241628365069

In [ ]:
test_data.head()

In [ ]:
train_data.tail()

In [ ]:
train_test_data = train_data.append(test_data, ignore_index=True)
train_test_data['clean_text'].fillna(" ", inplace=True)

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(train_test_data.clean_text)
tf_idf = pd.DataFrame(data = X.toarray(), columns=vectorizer.get_feature_names())
tf_idf

In [ ]:
tf_idf_featured = pd.concat([train_test_data, tf_idf], axis=1)
tf_idf_featured

In [ ]:
tf_idf_featured.drop(['index', 'id_original', 'text_original', 'clean_text', 'keyword_original', 'location_original', 'hashtags', 'labels'], axis=1, inplace=True)

In [ ]:
train = tf_idf[:7613]
test = tf_idf[7613:]

In [ ]:
train

In [ ]:
test

In [ ]:
clf = MultinomialNB()
clf.fit(train, train_data.target_label)

In [ ]:
predicted = clf.predict(test)

In [ ]:
test_data['target'] = predicted
test_data[['id_original', 'target']].rename(columns={'id_original': 'id'}).to_csv('~/Documents/Datos/DataSets/TP2/res_NB_2.csv', index=False)